### ISSUE TITLE
[Issue]: Honey Generator Infinite Honey Bug

### ISSUE THREAD

**Issue by vicdum** [The-Nexus-Project/Limitless-8#10]
### What happened?

If you put honey bucket in honey generator, honey bucket not consumed. Bucket gives infinitly honey to honey generator.

![image](https://github.com/user-attachments/assets/cbfcaf21-6c7d-4404-98aa-e4fcc7d9f7cd)

### Pack Version

Version: 0.15.0

### To Reproduce

1.

### Are you using Oculus?

- [ ] Yes. I am using Oculus.
- [X] No. Unmodified instance.

### Are you on a Server?

- [X] Yes.
- [ ] No.

**Comment by TelepathicGrunt** [comment]
@JaisDK I set a craft remainder on my honey bucket. Is your generator not checking for craft remainders and/or usingConvertsTo items?
https://github.com/TelepathicGrunt/Bumblezone/blob/c2d25d19155a2b4ba6307aa730a297970e94f2f2/common/src/main/java/com/telepathicgrunt/the_bumblezone/modinit/BzItems.java#L160

**Comment by JaisDK** [comment]
it should be fixed in yesterdays release
