### ISSUE TITLE
[Issue]: Plus in EMI crafting preview not showing in Crafting Station

### ISSUE THREAD

**Issue by FeineKatze** [The-Nexus-Project/Limitless-8#13]
### What happened?

When I open the recipe screen for any craftable item in EMI while in the crafting station the little plus doesn't pop up

### Pack Version

Version: 0.15.0

### To Reproduce

1. open world
2. go into the crafting station crafting screen
3. open the emi recipe screen for something craftable
4. the little plus doesn't show up

### Are you using Oculus/Iris?

- [ ] Yes. I am using Oculus/Iris.
- [X] No. My instance is unmodified, stock install.

### Are you on a Server?

- [ ] Yes.
- [X] No.

### whole latest.log output & crash report.

```shell
https://gist.github.com/FeineKatze/4d8631dfa468990f89b0ca42e55ba03b
```

**Comment by Gbergz** [comment]
EMI was removed in pack version 0.15.0

**Comment by Gbergz** [comment]
And this "issue" is however intended by the mod developer, the + sign is missing on purpose.

**Comment by Gbergz** [comment]
Once this mod updates: https://legacy.curseforge.com/minecraft/mc-mods/crafting-station-jei-edition

I will replace current Craft Station mod with it.
