### ISSUE TITLE
[Issue]: Modded Enderpearls don't work in crafting stuff

### ISSUE THREAD

**Issue by Mr-Simplex** [The-Nexus-Project/Limitless-8#16]
### What happened?

Many of the crafting recipes inside the pack do not work with the Enderman Overhaul enderpearls. For instance, if you want to go to the end, you can't make eyes of ender with the modded pearls, you need to find vanilla pearls instead. Or if you wish to make a waystone you can't use modded pearls either - you have to use vanilla ones. (and overall the vanilla pearls are very very difficult to find)

### Pack Version

Version: 0.16.0

### To Reproduce

1. Install pack
2. Kill Enderman Overhaul endermen
3. Attempt to craft Eyes of Ender with the pearls

### Are you using Oculus/Iris?

- [ ] Yes. I am using Oculus/Iris.
- [X] No. My instance is unmodified, stock install.

### Are you on a Server?

- [ ] Yes.
- [X] No.

### Anything else to add?

I know this is technically also an issue with the mod author, rather than modpack creators, but it would be nice if we could at least getting a solution for the meantime until they fix it.

**Comment by Gbergz** [comment]
Pretty sure that is on purpose from the mod developer, so I would check with them.

**Comment by Mr-Simplex** [comment]
I was just wondering if it was a modpack issue since you could always add an extra recipe to control progression the way you would like. Fair enough if this is intentional behaviour though, I can submit a request to the mod author too.

**Comment by Gbergz** [comment]
I will check the behavior of the pearls in 1.20.1 and get back to you, if it’s the same there it is indeed intended. But I can adjust recipes to make them usable in recipes where only vanilla pearl would be. Small useful QOL feature.

**Comment by Gbergz** [comment]
There were some issues with replacing every input with the enderpearls tag so I atleast added a recipe to make Ender Eyes with the modded pearls. Added in v0.19.0

**Comment by Ash-Olorenshaw** [comment]
Nice, thanks!

**Comment by Mr-Simplex** [comment]
> There were some issues with replacing every input with the enderpearls tag so I atleast added a recipe to make Ender Eyes with the modded pearls. Added in v0.19.0

Thanks for the changes, I can finally conquer the End now haha
