### ISSUE TITLE
[Issue]: Mystical Agriculture Silicon Seeds not craftable.

### ISSUE THREAD

**Issue by neilwightman** [The-Nexus-Project/Limitless-8#18]
### What happened?

The recipe for silicon seeds only accepts enderio:silicon, but this isn't craftable.   Only ae2:silicon can be made in a furnace.

### Pack Version

Version: Limitless 9 - v0.21.0

### To Reproduce

1. Make 4 silicon, 4 Prudential Essence and 1 properity seed.
2. Put all items in to Infusion Alter and Pedestals.
3. Give the alter a redstone signal.
4. Nothing will happen.

### Are you using Iris? (For shaders).

- [ ] Yes. I am using Iris.
- [X] No. My instance is unmodified, stock install.

### Are you on a Server?

- [ ] Yes.
- [X] No.

**Comment by Gbergz** [comment]
This was posted in our [discord](https://discord.gg/gwzpyQb) aswell, will be fixed most likely next update!

Thanks for report.

**Comment by neilwightman** [comment]
This can be closed with the newest update.  Its working again :)

**Comment by Gbergz** [comment]
Yes indeed, forgot to reply here after posting the update. :)
