### ISSUE TITLE
[Issue]: Garden Cloche instantly crash

### ISSUE THREAD

**Issue by FreecerFX** [The-Nexus-Project/Limitless-8#22]
### What happened?

A bug happened!

### Pack Version

Version: latest (31.10.2024)

### To Reproduce

1.Build Setup for Garden Cloche
2.Use it
3.Crash (it crashes instantly, i cant join the Server anymore)

### Are you using Iris? (For shaders).

- [ ] Yes. I am using Iris.
- [x] No. My instance is unmodified, stock install.

### Are you on a Server?

- [x] Yes.
- [ ] No.

### whole latest.log output & crash report.

```shell
https://pastebin.com/QZYSxMA0
```

**Comment by Gbergz** [comment]
https://github.com/The-Nexus-Project/Limitless-8/issues/21
