### ISSUE TITLE
[Issue]: .25 Jetpack error

### ISSUE THREAD

**Issue by aAndrew3030** [The-Nexus-Project/Limitless-8#23]
### What happened?

Updating the pack to .25 caused my jetpack to be "undefined", and the jetpack recipes to disappear. Reverting the mods Jetpacks back to 8.0.4 and Cucumber to 8.0.6 fixed the issue

### Pack Version

Version: .25

### Are you using Iris? (For shaders).

- [ ] Yes. I am using Iris.
- [ ] No. My instance is unmodified, stock install.

### Are you on a Server?

- [ ] Yes.
- [X] No.

**Comment by Gbergz** [comment]
Thanks for report! This is known however, it will be adjusted next update, that being a hotfix or next regular update we'll see.
