### ISSUE TITLE
[Issue]: 

### ISSUE THREAD

**Issue by Kyzoku** [The-Nexus-Project/Limitless-8#27]
### What happened?

There is no recipe in JEI for Bank Link from Bank Storage mod.

### Pack Version

Version: 0.25.0

### To Reproduce

1. Open JEI and click to view recipe.

### Are you using Iris? (For shaders).

- [ ] Yes. I am using Iris.
- [X] No. My instance is unmodified, stock install.

### Are you on a Server?

- [ ] Yes.
- [X] No.

### Anything else to add?

I looked into this and the author of the Bank Storage mod states that JEI is unsupported and recommends EMI.

**Comment by Gbergz** [comment]
Bank Storage doesn't support JEI.
