### ISSUE TITLE
[Issue]: Typing in creative menu crashes the game

### ISSUE THREAD

**Issue by GalaxyboyYTGH** [The-Nexus-Project/Limitless-8#3]
### What happened?

Exactly what it says in the title 

### Pack Version

Version: TNP Limitless 8 0.9.0

### To Reproduce

1. Start typing in the creative search items menu

### Are you using Oculus?

- [ ] Yes. I am using Oculus.
- [x] No. Unmodified instance.

### Are you on a Server?

- [ ] Yes.
- [x] No.

**Comment by Gbergz** [comment]
0.9.0 is archived due to issues. Please rollback to 0.8.0 for now.
