### ISSUE TITLE
[Issue]: Missing butter and cheese recipe components

### ISSUE THREAD

**Issue by wizardofdocs** [The-Nexus-Project/Limitless-8#33]
### What happened?

The recipes for cheese in both Croptopia and Extra Delight, as well as Croptopia's butter recipe, are missing components.
Croptopia cheese and butter both require the empty tag c:salts.
Extra Delight cheese requires vinegar, which has no crafting recipe.
These items being uncraftable limits player food options and reduces the potential HP gain from Spice of Life.

### Pack Version

Version: 0.30.0

### To Reproduce

1. Open JEI.
2. Search JEI for "cheese @croptopia".
3. Click the cheese item. The recipe shows an empty tag for salt.
4. Search JEI for "butter @croptopia".
5. Click the butter item. The recipe is identical to the cheese recipe, including the empty salt tag.
6. Search JEI for "cheese @extra".
7. Click the cheese item.
8. In the recipe popup, click the Farmer's Delight cooking tab.
9. Click the vinegar item in the recipe. There is an option to craft it from a bucket of vinegar and four bottles.
10. Click the vinegar bucket item in the new recipe. There is an option to craft it from four vinegar items and a bucket, and an Extended Industrialization canning recipe. There is no way to make vinegar from something that isn't vinegar.

### Are you using Iris? (For shaders).

- [ ] Yes. I am using Iris.
- [X] No. My instance is unmodified, stock install.

### Are you on a Server?

- [ ] Yes.
- [X] No.

**Comment by Gbergz** [comment]
Thanks for report!
Salt empty tag issues will be resolved next update (v0.31.0)

**Comment by Gbergz** [comment]
That update is out now.
