### ISSUE TITLE
[Issue]: Client Crash When Scrolling Through Mod List in Mod Config

### ISSUE THREAD

**Issue by YookuMC** [The-Nexus-Project/Limitless-8#4]
### What happened?

I have encountered an issue with the client when using the Mod config feature.

The client crashes consistently when scrolling through the list of mods 

### Pack Version

Version: 0.9.0

### To Reproduce

1. Open the client.
2. Go to the Mod config section.
3. Start scrolling through the list of mods.

### Are you using Oculus?

- [ ] Yes. I am using Oculus.
- [X] No. Unmodified instance.

### Are you on a Server?

- [ ] Yes.
- [X] No.

### Relevant log output / crash report.

```shell
The game crashed whilst rendering screen
Error: java.lang.RuntimeException: java.io.IOException: Bad PNG Signature
```

**Comment by Gbergz** [comment]
Known. Don't scroll through it right now.

**Comment by Gbergz** [comment]
Edit configs in the config folder and not in-game for now.
