### ISSUE TITLE
Fuel only smelts 0,5 items instead of 8.

### ISSUE THREAD

**Issue by Jocky69** [The-Nexus-Project/Limitless-8#6]
Just to know if it's normal that 1 coal doesn't burn 1 i raw beef?

**Comment by Gbergz** [comment]
Definitely not normal, some mod probably accidentally overrides it... bummer.

**Comment by Gbergz** [comment]
Seems anything only smelts 0,5 items.. hm weird.

**Comment by Jocky69** [comment]
Yes really strange

**Comment by Jocky69** [comment]
ok thanks

**Comment by Gbergz** [comment]
Not HUGE issue, but annoying nonetheless, I will investigate.

**Comment by Jocky69** [comment]
Great. I will wait for an update. Have a nice day.

**Comment by Gbergz** [comment]
v0.9.0 shouldn't have this issue if you wanna play on that version. Your choice until this is fixed.

**Comment by Jocky69** [comment]
i'll see. Not in a hurry, for the food, i'm using a camp fire. Can you add coal chunk, should be great too. ;)

**Comment by Gbergz** [comment]
Found the mod causing it, and I've reported it here: https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/issues/174

**Comment by Jocky69** [comment]
Thanks. Do i remove it temporarly?

**Comment by Gbergz** [comment]
You can, but start a new world if so.

**Comment by Jocky69** [comment]
Ok. only (regions_unexplored-neoforge-1.21-0.5.6)  or  both  (TerraBlender-neoforge-1.21-4.0.0.1) ?

**Comment by Jocky69** [comment]
Thanks. I'll do that. Have a nice day.

**Comment by Jocky69** [comment]
Ah ok.
