### ISSUE TITLE
[Issue]: Pylons - Harvester Plyon not breakable and non-accessible inventory

### ISSUE THREAD

**Issue by SuperEpicJam** [The-Nexus-Project/Limitless-8#8]
### What happened?

A bug happened!

### Pack Version

Version: 

### To Reproduce

1.

### Are you using Oculus?

- [ ] Yes. I am using Oculus.
- [ ] No. Unmodified instance.

### Are you on a Server?

- [x] Yes.
- [ ] No.

**Comment by Gbergz** [comment]
Report to Pylon dev.
