### ISSUE TITLE
[Issue]: Mystical Aggriculture soul jars cannot be filled in the soul extractor

### ISSUE THREAD

**Issue by SuperEpicJam** [The-Nexus-Project/Limitless-8#9]
### What happened?

A bug happened!

### Pack Version

Version: 

### To Reproduce

1.

### Are you using Oculus?

- [ ] Yes. I am using Oculus.
- [ ] No. Unmodified instance.

### Are you on a Server?

- [X] Yes.
- [ ] No.

**Comment by Gbergz** [comment]
Report to Mystical Agriculture dev.
